version: "3.8"

services:
  mongo1:
    image: mongo:4.2
    container_name: mongo1
    command: ["--replSet", "crowdfarming-local-dev", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'crowdfarming-local-dev',members:[{_id:0,host:\"mongo1:27017\"},{_id:1,host:\"mongo2:27018\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G

  mongo2:
    image: mongo:4.2
    container_name: mongo2
    command: ["--replSet", "crowdfarming-local-dev", "--bind_ip_all", "--port", "27018"]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 27018:27018
    deploy:
      resources:
        limits:
          memory: 1G
